export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';

export const UPDATE_COURSES_FAILURE = 'UPDATE_COURSES_FAILURE';

export const UPDATE_ADS_SUCCESS = 'UPDATE_ADS_SUCCESS';

export const UPDATE_ADS_FAILURE = 'UPDATE_ADS_FAILURE';