services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8082:8082"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public/adminpanel:/app/adminpanel    

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - .:/app


  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    env_file:
      - ./.env/.env


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - ./.env/.env

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./python/adminpanel:/app




volumes:
  mysqldata: